var trials = [
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "bluehouse_bluehouse(twice?)",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "househouse",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "bluehouse_bluehouse",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "househouse",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "greentree_greentree",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "treetree",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "redcar_redcar",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "carcar",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "bluehouse_greentree",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "housetree",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "blueness",
    "target_picture": "bluehouse_redcar",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "housecar",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "redcar_redcar",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "carcar",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "redcar_redcar",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "carcar",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "bluehouse_bluehouse",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "househouse",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "greentree_greentree",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "treetree",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "redcar_bluehouse",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "carhouse",
    "foil_object": "NA"
  },
  {
    "phase": "testing",
    "sentence": "redness",
    "target_picture": "redcar_greentree",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "cartree",
    "foil_object": "NA"
  },
  {
    "phase": "training",
    "sentence": "greenness",
    "target_picture": "bluecastle_bluecastle",
    "foil_picture": "greenbicycle_greenbicycle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "castlecastle",
    "foil_object": "bicyclebicycle"
  },
  {
    "phase": "training",
    "sentence": "greenness",
    "target_picture": "greenbicycle_greenbicycle",
    "foil_picture": "bluecastle_bluecastle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "bicyclebicycle",
    "foil_object": "castlecastle"
  },
  {
    "phase": "training",
    "sentence": "greenness",
    "target_picture": "redflower_redflower",
    "foil_picture": "greenbicycle_greenbicycle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "flowerflower",
    "foil_object": "bicyclebicycle"
  },
  {
    "phase": "training",
    "sentence": "greenness",
    "target_picture": "greenbicycle_greenbicycle",
    "foil_picture": "redflower_redflower",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "bicyclebicycle",
    "foil_object": "flowerflower"
  }
]