var trials = [
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_green_triangle, green_blue_triangle, blue_red_triangle, red_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_red_square, red_blue_square, blue_green_square, green_blue_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the star is",
    "target_picture": "blue_green_star, green_blue_star, blue_red_star, red_blue_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the circle is",
    "target_picture": "blue_red_circle, red_blue_circle, blue_green_circle, green_blue_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_blue_triangle, blue_red_triangle, red_green_triangle, green_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_green_square, green_red_square, red_blue_square, blue_red_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the star is",
    "target_picture": "red_blue_star, blue_red_star, red_green_star, green_red_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the circle is",
    "target_picture": "red_green_circle, green_red_circle, red_blue_circle, blue_red_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_green_triangle, green_blue_triangle, blue_red_triangle, red_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_red_square, red_blue_square, blue_green_square, green_blue_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the star is",
    "target_picture": "blue_green_star, green_blue_star, blue_red_star, red_blue_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the circle is",
    "target_picture": "blue_red_circle, red_blue_circle, blue_green_circle, green_blue_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_blue_triangle, blue_red_triangle, red_green_triangle, green_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_green_square, green_red_square, red_blue_square, blue_red_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the star is",
    "target_picture": "red_blue_star, blue_red_star, red_green_star, green_red_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the circle is",
    "target_picture": "red_green_circle, green_red_circle, red_blue_circle, blue_red_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the triangle is",
    "target_picture": "blue_green_triangle, green_blue_triangle, blue_red_triangle, red_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the square is",
    "target_picture": "blue_red_square, red_blue_square, blue_green_square, green_blue_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the star is",
    "target_picture": "blue_green_star, green_blue_star, blue_red_star, red_blue_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The blueness of the circle is",
    "target_picture": "blue_red_circle, red_blue_circle, blue_green_circle, green_blue_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "blue_blue_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the triangle is not",
    "target_picture": "green_green_triangle, red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The blueness of the square is not",
    "target_picture": "red_red_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the triangle is",
    "target_picture": "red_blue_triangle, blue_red_triangle, red_green_triangle, green_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the square is",
    "target_picture": "red_green_square, green_red_square, red_blue_square, blue_red_square",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the star is",
    "target_picture": "red_blue_star, blue_red_star, red_green_star, green_red_star",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "star",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "positive",
    "sentence": "The redness of the circle is",
    "target_picture": "red_green_circle, green_red_circle, red_blue_circle, blue_red_circle",
    "foil_picture": "NA",
    "expected_answer": "?",
    "meaning": "Some/NAll",
    "trial_type": "extrapolation",
    "ET": "E",
    "target_object": "circle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "red_red_triangle",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "red_red_square",
    "foil_picture": "NA",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the triangle is not",
    "target_picture": "green_green_triangle, blue_blue_triangle",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "triangle",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "testing",
    "type_sentence": "negative",
    "sentence": "The redness of the square is not",
    "target_picture": "blue_blue_square, green_green_square",
    "foil_picture": "NA",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "E",
    "target_object": "square",
    "foil_object": "NA"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star, red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star, red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle, blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 1",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle, blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the star is",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 2",
    "phase": "training",
    "type_sentence": "positive",
    "sentence": "The greenness of the circle is",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "blue_blue_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "blue_blue_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "blue_blue_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "blue_blue_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "red_red_star",
    "foil_picture": "green_green_star",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the star is not",
    "target_picture": "green_green_star",
    "foil_picture": "red_red_star",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "star",
    "foil_object": "star"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "red_red_circle",
    "foil_picture": "green_green_circle",
    "expected_answer": "ALL",
    "meaning": "All",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  },
  {
    "experiment": "experiment 3",
    "phase": "training",
    "type_sentence": "negative",
    "sentence": "The greenness of the circle is not",
    "target_picture": "green_green_circle",
    "foil_picture": "red_red_circle",
    "expected_answer": "NONE",
    "meaning": "None",
    "trial_type": "not_extrapolation",
    "ET": "T",
    "target_object": "circle",
    "foil_object": "circle"
  }
]
// Function to randomly select one of the pictures from the "target_picture" field
function selectRandomPicture(trial) {
  // Split the "target_picture" field by comma to get individual picture options
  var pictureOptions = trial.target_picture.split(', ');
  // Randomly select one of the picture options
  var randomIndex = Math.floor(Math.random() * pictureOptions.length);
  // Return the randomly selected picture
  return pictureOptions[randomIndex];
}

// Loop through each trial object and update the "target_picture" field with a randomly selected picture
for (var i = 0; i < trials.length; i++) {
  //console.log(trials[i].target_picture)
  trials[i].target_picture = selectRandomPicture(trials[i]);
  //console.log(trials[i].target_picture)

}

// Function to randomly select one of the pictures from the "foil_picture" field
function selectRandomFoilPicture(trial) {
  // Split the "foil_picture" field by comma to get individual picture options
  var pictureOptions = trial.foil_picture.split(', ');
  // Randomly select one of the picture options
  var randomIndex = Math.floor(Math.random() * pictureOptions.length);
  // Return the randomly selected picture
  return pictureOptions[randomIndex];
}

// Loop through each trial object and update the "foil_picture" field with a randomly selected picture
for (var i = 0; i < trials.length; i++) {
  trials[i].foil_picture = selectRandomFoilPicture(trials[i]);
}